GET http://localhost:3001/posts
Authorization: Bearer

###

POST http://localhost:4001/token
Content-Type: application/json

{
    "token": ""
}

###

POST http://localhost:4001/login
Content-Type: application/application/json

{
    "username": "Kyle"
}
